#!/bin/sh

# see the -detached flag

# Cluster (rubik)
# ./startenviron \
#   -sname temp -config configs/rubik -detached -noinput -boot environ

# Regular
# ./startenviron -noinput -boot environ

# interactive
erl "$@" -mnesia dir "\"$HOME/tmp/mnesia\"" \
	-pa $HOME/lib/erlang/smtp_client-1.1/ebin/ \
	-pa apps/lemp -pa apps/temp_listener -pa apps/env_alert -boot environ
