#!/bin/sh
#
# arch-tag: B8E4F73A-9D9B-11D8-B7F1-000A957659CC

# see the -detached flag

# Cluster (rubik)
# ./startenviron \
#   -sname temp -config configs/rubik -detached -noinput -boot environ

# Regular
# ./startenviron -noinput -boot environ

# interactive
erl "$@" -pa $HOME/lib/erlang/smtp_client-1.1/ebin/ \
	-pa apps/lemp -pa apps/temp_listener -pa apps/env_alert -boot environ
