#!/bin/sh
#
# arch-tag: B8E4F73A-9D9B-11D8-B7F1-000A957659CC

# see the -detached flag

# Cluster (rubik)
# erl "$@" -sname temp -config rubik -detached -noinput -boot environ

# Regular
# erl "$@" -noinput -boot environ

# interactive
erl "$@" -boot environ
